on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build GitHub Action
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Nexploit Scan Start
        id: start
        uses: NeuraLegion/run-scan@release
        with:
          api_token: ${{ secrets.NEXPLOIT_TOKEN}}
          hostname: development.playground.nexploit.app
          # restart_scan: 2BEAaXGsH3rxb46aufk2Yw
          name: Sarif - wait-for test (NL-1020) - ${{ github.sha }}
          discovery_types: |
            [ "archive" ]
          # crawler_urls: |
          #   [ "https://brokencrystals.com" ]
          module: 'dast'
          file_id: xiAnxPimcn6v8khFv5FcvA
      - name: Wait for any issues ⏳
        id: wait
        uses: NeuraLegion/wait-for@release
        with:
          api_token:  ${{ secrets.NEXPLOIT_TOKEN }}
          hostname: development.playground.nexploit.app
          scan: ${{ steps.start.outputs.id }}
          wait_for: medium
          timeout: 300
      # - name: Nexploit Stop Scan
      #   uses: NeuraLegion/stop-scan@release
      #   with:
      #     api_token: ${{ secrets.NEXPLOIT_TOKEN }}
      #     hostname: development.playground.nexploit.app
      #     scan: ${{ steps.start.outputs.id }}
